### ISSUE TITLE
Y axis range in fitPlot not accounting for prediction interval

### ISSUE THREAD

**Issue by sumnonpuella** [droglenc/NCStats#3]
When plotting SLR results with both confidence and prediction intervals, if the range the prediction interval on the y axis reaches beyond the min/max y axis range of the dataset, fitPlot will not account for this, and the resulting plot will exclude the prediction interval. 

Example: 
fitPlot Default 
`fitPlot(slr_lm, interval="both", xlab = "Median Elevation (m a.s.l.)", ylab ="Front Line Variation (m)")`
![image](https://user-images.githubusercontent.com/10407726/38947896-ba8ea126-4303-11e8-83b9-a3e9a765a65e.png)

Manually Adjusted 
`fitPlot(slr_lm, interval="both", xlab = "Median Elevation (m a.s.l.)", ylab ="Front Line Variation (m)", ylim=c(-70, 30))`
![image](https://user-images.githubusercontent.com/10407726/38947916-cdd383b4-4303-11e8-92a1-0255238da41f.png)

**Comment by droglenc** [comment]
Similar problem with `predictionPlot()`

**Comment by droglenc** [comment]
This issue is actually with `fitPlot()` in the `FSA` package. It will be fixed once FSA v0.8.23 is released.
